### Create user

POST http://{{host}}/auth/signup
Content-Type: application/json

{
    "email": "benjamin.nosel@adriver.co",
    "password": "Adriver@2022"
}

### singin User

POST http://{{host}}/auth/signin
Content-Type: application/json

{
    "email": "benjamin.nosel@adriver.co",
    "password": "Adriver@2022"
}

### singout User

POST http://{{host}}/auth/signout

### Get user by ID

GET http://{{host}}/auth/2

### Get users with query string

GET http://{{host}}/auth?email=test@gmail.com

### Update user by id

PATCH http://{{host}}/auth/1
Content-Type: application/json

{
    "email": "test@hotmail.fr"
}

### Delete user by id

DELETE http://{{host}}/auth/1

### Get current signed user

GET http://{{host}}/auth/whoami
